Repository gardener/sow, pull requests merged in 2021-04, with the labels that each got.

#39 Update Makefile.
  Makefile
Labels: needs/review, size/xs

#40 Support for PPC64LE image creation
  Makefile
  docker/Dockerfile
Labels: needs/changes, needs/review, size/xs

#41 terraform plugin: relative source + direct main spec
  README.md
  bin/sow
  lib/action
  lib/utils
  plugins/terraform/README.md
  plugins/terraform/plugin
Labels: reviewed/lgtm, size/m

#42 Update kubectl in sow image to 1.17.16 to support cert-manager
  docker/Dockerfile
Labels: needs/review, size/xs
